FROM ubuntu:14.04
MAINTAINER "jin <jin@sample.cloud>"
LABEL "purpose"="webserver practice"
RUN apt-get update && apt-get install apache2 -y && \
    apt-get clean -y && \
    apt-get autormove -y && \
    rm -rfv /tmp/* /var/lib/apt/list/* /var/tmp/*
WORKDIR /var/www/html
ADD index.html .
EXPOSE 80
CMD apachectl -D FOREGROUND
